# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SixSq Website
year: 2023
email: info@sixsq.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sixsq.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sixsq

calendly-href: https://calendly.com/nuvla-io-demo/30min?hide_gdpr_banner=1
google-tag-id: GTM-M77XBLH

blog-discover: discover
blog-tech-corner: tech-corner
blog-marketplace: marketplace

excerpt_separator: <!--more-->

# Search exclude
exclude_urls:
  - /blog/casestudies/index.html
  - /blog/feature/index.html
  - /blog/hardware/index.html
  - /blog/job/index.html
  - /blog/news/index.html
  - /blog/nuvla-marketplace/index.html
  - /blog/partner/index.html
  - /blog/tag/casestudies/index.html
  - /404.html


collections:
  partners:
    output: false
  vendors:
    output: false
  customers:
    output: false
  nuvlaedge:
    output: false
  marketplace:
    output: false
  platform:
    output: false
  casestudies:
    output: true
  casestudies-benefits:
    output: false
  jobs:
    output: true
  authors:
    output: true
  legal:
    output: true
  rd:
    output: true
  staff:
    output: false
    

defaults:
  -
    scope:
      path: news
      type: posts
    values:
      category: news
      layout: news-article
      product-name: News
      location: Geneva, Switzerland
      author-name: Louise Merifield
      author-email: merifield@sixsq.com
      author-title: Co-founder &amp; Operations Manager
      author-mobile: +41 77 44 68 170
      breadcrumbs:
       - name: Home
         target: /
       - name: News
         target: /news
      without-trial: true
      they-trust-us: false
  -
    scope:
      path: blog
      type: posts
    values:
      category: blog
      layout: blog-article
      product-name: Blog
      location: Geneva, Switzerland
      without-trial: true
      they-trust-us: false
      breadcrumbs:
       - name: Home
         target: /
       - name: Blog
         target: /blog
      without-trial: true
      they-trust-us: false
  -
    scope:
      path: "*/features"
      type: "nuvlaedge"
    values:
      category: "feature"
  -
    scope:
      path: "*/hardware"
      type: "nuvlaedge"
    values:
      category: "hardware"
  -
    scope:
      path: "*/features"
      type: "marketplace"
    values:
      category: "feature"
  -
    scope:
      path: "*/features"
      type: "platform"
    values:
      category: "feature"
  -
    scope:
      path: ""
      type: casestudies
    values:
      product-name: Case study
      category: casestudy
      breadcrumbs:
       - name: Home
         target: /
       - name: Case Studies
         target: /case-studies
  -
    scope:
      path: ""
      type: jobs
    values:
      layout: job
      category: job
      product-name: Job
      product-background-img: bg-hero-jobs.jpg
      without-trial: true
      breadcrumbs:
       - name: Home
         target: /
       - name: Jobs
         target: /jobs
      without-trial: true
      they-trust-us: false
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      product-name: Blog Author
      product-background-img: bg-hero-blog.jpg
      breadcrumbs:
       - name: Home
         target: /
       - name: Blog
         target: /blog
      without-trial: true
      they-trust-us: false
  -
    scope:
      path: ""
      type: legal
    values:
      layout: legal-article
      product-name: Legal &amp; Terms
      product-background-img: bg-hero-legal.jpg
      breadcrumbs:
       - name: Home
         target: /
       - name: Legal &amp; Terms
         target: /legal
      without-trial: true
      they-trust-us: false
  -
    scope:
      path: ""
      type: rd
    values:
      layout: r&d-article
      product-name: R&amp;D Project
      product-background-img: bg-hero-rd.jpg
      breadcrumbs:
       - name: Home
         target: /
       - name: R&amp;D
         target: /r&d
      without-trial: true
      they-trust-us: false
  -
    scope:
      path: ""
      type: partners
    values:
      category: partner
  -
    scope:
      path: ""
      type: vendors
    values:
      category: Nuvla-marketplace
      permalink: /marketplace#app-vendors
  -
    scope:
      path: "*/manufacturing"
      type: casestudies-benefits
    values:
      permalink: /case-studies/manufacturing
  -
    scope:
      path: "*/retail"
      type: casestudies-benefits
    values:
      permalink: /case-studies/retail
  -
    scope:
      path: "*/transport"
      type: casestudies-benefits
    values:
      permalink: /case-studies/transport


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 9

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ''

 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

autopages:

  # Site-wide kill switch, disable here and it doesn't run at all
  enabled: true

  # Category pages, omit entire config element to disable
  categories:
#    enabled: false
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts:
      - 'blog-category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: ':cat'
    # Optional, the permalink for the  pagination page (:cat is replaced),
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/blog/:cat'
    # Optional, when true logging related to category pages will be supressed.
    silent: false
    slugify:
      mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false       # Whether to replace all uppercase letters with their lowercase counterparts

  # Collection pages, omit to disable
  collections:
    enabled: false
    layouts:
      - 'blog.html'
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    pagination: 
      enabled: true
      permalink: ':num/'
    permalink: '/blog/:coll'
    silent: false
    slugify:
      mode: 'default'   # :coll is slugified.
      case: false

  # Tag pages, omit to disable
  tags:
    layouts:
      - 'blog-tag.html'
    title: ':tag'
    pagination: 
      enabled: true
      permalink: ':num/'
    tag: ':tag'
    without-trial: true
    permalink: '/blog/tag/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false
